apiVersion: apps/v1
kind: Pod

metadata:
  name: long-term-load-injector
spec:
  ttlSecondsAfterFinished: 10
  containers:
  - name: long-term-load-injector
    image: docker.io/library/event-driven-load-injector:local
    args: ["${WORKLOAD_NUMBER}", "${MODEL}"]
    imagePullPolicy: Never
    resources:
      requests:
        cpu: 0
      limits:
        cpu: 1