---
- name: Prepare event driven simulation
  hosts: all 
  gather_facts: true
  become: true
  roles:
    - role: simulation_prereq
    - role: system_measurments

- name: Run event driven simulation
  hosts: server
  gather_facts: true
  become: true
  roles:
    - role: simulation 