---
- name: Setup Wi-Fi connection
  hosts: all
  become: true
  vars_prompt:
      - name: network_identity
        prompt: Enter value for network_identity
        private: false
      - name: network_password
        prompt: Enter value for network_password
  roles:
      - role: network
        tags: [network]

- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
      - role: prereq
      - role: airgap
      - role: raspberrypi
  vars_files:
      - secret.yml

- name: Setup K3S server
  hosts: master
  become: true
  roles:
      - role: k3s_server
  vars:
      label: model=rpi4b

- name: Setup K3S rpi4b agent
  hosts:
      - rpi4b-worker
  become: true
  roles:
      - role: k3s_agent
  vars:
      label: model=rpi4b

- name: Setup K3S rpi5 agent
  hosts: rpi5-worker
  become: true
  roles:
      - role: k3s_agent
  vars:
      label: model=rpi5
